### ISSUE TITLE
Secure Lockscreen Trigger

### ISSUE THREAD

**Issue by sebi673** [nerfherder/BluetoothGoogleNow#2]
First of all, the module made my day.... I've been trying for a long time to change the redial fn to g.now voice prompt. It simply works - on stock Xperia Z 5.11. Thank you so much for your work! :grinning: 

But will we see an update supporting google now trigger in secure lockscreen? For now it only turns the screen on. I worked around the issue by disabling lockscreen on trusted devices. but I was wondering if in the future it will work without all the hassle. Or if there is anything I could do to make it work. Thank's a lot!! :smiley:

**Comment by nerfherder** [comment]
No worries, I made this module a while ago but only just got around to uploading and sharing it - seems I should have done it earlier. I am working on trying to get around the lockscreen issue as we speak but so far no luck.

**Comment by nerfherder** [comment]
I have pushed through a new update which should work.
